<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Clique em , , Confirmar, ,  quan_9cd048_1_2</name>
   <tag></tag>
   <elementGuidId>6abee347-bb7c-44e7-81c6-2f4591073024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26WuDfOvuSI29PB6U6yN-8fvbmP2cNYlDlQiA6gtGUo0qLh0QvJaUV6vH5GXRzhRp0ZXPieDGdZ2cOxIpye4q23vtdIws_tZ52J_nHdGnIrT5k_dEkL0LsfJHX1mr7DQVJkyAgeZV9MVjwY0sS9Qu7jcbZT6qGY-1-SKhpBx8letBDYCkZRRuxMc-zcyIPuFCAxRrzi&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Americanas.com - A Maior Loja da Inter_5cd4ca/iframe_html1body1div3div2iframe1_c-xhze4imkb1r6</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26WuDfOvuSI29PB6U6yN-8fvbmP2cNYlDlQiA6gtGUo0qLh0QvJaUV6vH5GXRzhRp0ZXPieDGdZ2cOxIpye4q23vtdIws_tZ52J_nHdGnIrT5k_dEkL0LsfJHX1mr7DQVJkyAgeZV9MVjwY0sS9Qu7jcbZT6qGY-1-SKhpBx8letBDYCkZRRuxMc-zcyIPuFCAxRrzi&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
