<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Clique em , , Confirmar, ,  quan_9cd048_1</name>
   <tag></tag>
   <elementGuidId>553a9663-1462-4d80-bc76-b3981753fde8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27dYz-q8R0iRwukXE1o8S6WxgclgT1NE4ADoT4VshmgImfzD96n6LtGN9z-8HR0656vhc8-eaVzZJkmDdLkj4g0IX-LC8VopeWKYCNoMbveHg7cZtLeKh3gUNJgRBM2a7DxNb54a1uKggtNkj38jhoNe2LzA1g10QbGqYXYZj0CKnGgx5Ovh8CYBY1FlbX4W9c1NMLO&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Americanas.com - A Maior Loja da Inter_5cd4ca/iframe_html1body1div3div2iframe1_c-xhze4imkb1r6</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27dYz-q8R0iRwukXE1o8S6WxgclgT1NE4ADoT4VshmgImfzD96n6LtGN9z-8HR0656vhc8-eaVzZJkmDdLkj4g0IX-LC8VopeWKYCNoMbveHg7cZtLeKh3gUNJgRBM2a7DxNb54a1uKggtNkj38jhoNe2LzA1g10QbGqYXYZj0CKnGgx5Ovh8CYBY1FlbX4W9c1NMLO&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
