<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Clique em , , Confirmar, ,  quando no houver mais nenhuma.)_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>74ec8614-d562-46ac-9d36-208272c836b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq253IwN9P2b5NVGzE0cA6kIrh-AqKdLNcjPzvzwBOvdA36hiB9qpC0GIHBEgm6tBLgvgTwG9z7LvvcjjzNv8h-8mS_pAoBKcecMvX1yBCkOXrzdoa62AfNpCuUP0PvdPBPTqFMdaIc9qfXGmXRwT98yz_R1Jgxpeyrk05CrQ4gb78qesZb21sxpUGaUXglMLiT7YFDEv&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Americanas.com - A Maior Loja da Inter_5cd4ca/iframe_html1body1div3div2iframe1_c-xhze4imkb1r6</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq253IwN9P2b5NVGzE0cA6kIrh-AqKdLNcjPzvzwBOvdA36hiB9qpC0GIHBEgm6tBLgvgTwG9z7LvvcjjzNv8h-8mS_pAoBKcecMvX1yBCkOXrzdoa62AfNpCuUP0PvdPBPTqFMdaIc9qfXGmXRwT98yz_R1Jgxpeyrk05CrQ4gb78qesZb21sxpUGaUXglMLiT7YFDEv&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
