<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Clique em , , Confirmar, ,  quan_9cd048</name>
   <tag></tag>
   <elementGuidId>2a557760-7054-4e93-bd93-21c4ab021025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24udtngkRkbP68b7yO2PZdmowDGJgB8tzuKJzOangtgOiNBF6Q7LGBPMLOVfAIU-08rC0NY9cZzPSP0cwLxG-2n-DfYkrRfnwNWbjOoD1vzOf8OAfbdNaP7GD6ns0xLNxli6WA6fwIVrRlpkd6mNA5w5mOZ_nZ6hjKnUtrcv_neB34mH89-mxQolS9MHZHZqr6HruXH&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Americanas.com - A Maior Loja da Inter_5cd4ca/iframe_html1body1div3div2iframe1_c-xhze4imkb1r6</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24udtngkRkbP68b7yO2PZdmowDGJgB8tzuKJzOangtgOiNBF6Q7LGBPMLOVfAIU-08rC0NY9cZzPSP0cwLxG-2n-DfYkrRfnwNWbjOoD1vzOf8OAfbdNaP7GD6ns0xLNxli6WA6fwIVrRlpkd6mNA5w5mOZ_nZ6hjKnUtrcv_neB34mH89-mxQolS9MHZHZqr6HruXH&amp;k=6Lecgi4UAAAAADoy8olZEoD8T5dqynjjJajXSQHj')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
